# Site settings
author: OJ Jappah
title: My First Portfolio Project
header-img: img/home-bg.png
email: ojappah@gmail.com
copyright_name: OJ Jappah
description: > # this means to ignore newlines until "baseurl:"
  Friend Generator CLI Data Gem
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  ojappah

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
